project:
  name: "MyMCPProject"
  version: "1.0.0"
  defaultLanguage: "typescript"
  defaultTransport: "stdio"

source: "services/**/*.automcp.yaml"

generates:
  "generated/":
    plugins:
      - "server"
      - "client"
      - "openapi"
